[000] Add contributor in script js file
bongodev/vanilla-javascript-fall-2024 pull request #74
Opened 2024-12-08 17:06 UTC by nazma98

## Project Name:

### Description

### QA Steps

- [ ]

2024-12-08 17:27 UTC, Tamjidul-Islam approved these changes

2024-12-09 15:05 UTC, Armstrong104 commented on script.js
> +  }
Can we please add a comma ',' after 2nd curly braces in line 34 so that we don't get conflict.

2024-12-09 15:06 UTC, Armstrong104 requested changes
Please change according to the review. Thank you.

2024-12-10 05:54 UTC, nazma98 commented on script.js
> +  }
Thanks for pointing it out! I've fixed it.

2024-12-10 09:15 UTC, Armstrong104 commented on script.js
> +  }
Welcome. Keep doing the good work.

2024-12-10 09:15 UTC, Armstrong104 approved these changes

2024-12-13 11:14 UTC, merged